/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class Bounds {
	private Southwest southwest;

 	public void setSouthwest(Southwest southwest) {
		this.southwest = southwest;
	}

	public Southwest getSouthwest() {
		return southwest;
	}

	private Northeast northeast;

 	public void setNortheast(Northeast northeast) {
		this.northeast = northeast;
	}

	public Northeast getNortheast() {
		return northeast;
	}

}