/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class DirectionResponse {
    private Geocoded_waypointElement[] geocoded_waypoints;

    public void setGeocoded_waypoints(Geocoded_waypointElement[] geocoded_waypoints) {
        this.geocoded_waypoints = geocoded_waypoints;
    }

    public Geocoded_waypointElement[] getGeocoded_waypoints() {
        return geocoded_waypoints;
    }

    private RoutElement[] routes;

    public void setRoutes(RoutElement[] routes) {
        this.routes = routes;
    }

    public RoutElement[] getRoutes() {
        return routes;
    }

    private String status;

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

}