/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class Distance {
	private Integer value;

 	public void setValue(Integer value) {
		this.value = value;
	}

	public Integer getValue() {
		return value;
	}

	private String text;

 	public void setText(String text) {
		this.text = text;
	}

	public String getText() {
		return text;
	}

}