/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class End_location {
	private Double lat;

 	public void setLat(Double lat) {
		this.lat = lat;
	}

	public Double getLat() {
		return lat;
	}

	private Double lng;

 	public void setLng(Double lng) {
		this.lng = lng;
	}

	public Double getLng() {
		return lng;
	}

}