/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class Geocoded_waypointElement {
	private String geocoder_status;

 	public void setGeocoder_status(String geocoder_status) {
		this.geocoder_status = geocoder_status;
	}

	public String getGeocoder_status() {
		return geocoder_status;
	}

	private String[] types;

 	public void setTypes(String[] types) {
		this.types = types;
	}

	public String[] getTypes() {
		return types;
	}

	private String place_id;

 	public void setPlace_id(String place_id) {
		this.place_id = place_id;
	}

	public String getPlace_id() {
		return place_id;
	}

}