/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class LegElement {
	private StepElement[] steps;

 	public void setSteps(StepElement[] steps) {
		this.steps = steps;
	}

	public StepElement[] getSteps() {
		return steps;
	}

	private Distance distance;

 	public void setDistance(Distance distance) {
		this.distance = distance;
	}

	public Distance getDistance() {
		return distance;
	}

	private Duration duration;

 	public void setDuration(Duration duration) {
		this.duration = duration;
	}

	public Duration getDuration() {
		return duration;
	}

	private Object[] via_waypoint;

 	public void setVia_waypoint(Object[] via_waypoint) {
		this.via_waypoint = via_waypoint;
	}

	public Object[] getVia_waypoint() {
		return via_waypoint;
	}

	private Start_location start_location;

 	public void setStart_location(Start_location start_location) {
		this.start_location = start_location;
	}

	public Start_location getStart_location() {
		return start_location;
	}

	private String end_address;

 	public void setEnd_address(String end_address) {
		this.end_address = end_address;
	}

	public String getEnd_address() {
		return end_address;
	}

	private String start_address;

 	public void setStart_address(String start_address) {
		this.start_address = start_address;
	}

	public String getStart_address() {
		return start_address;
	}

	private End_location end_location;

 	public void setEnd_location(End_location end_location) {
		this.end_location = end_location;
	}

	public End_location getEnd_location() {
		return end_location;
	}

}