/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class Polyline {
	private String points;

 	public void setPoints(String points) {
		this.points = points;
	}

	public String getPoints() {
		return points;
	}

}