/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class RoutElement {
	private LegElement[] legs;

 	public void setLegs(LegElement[] legs) {
		this.legs = legs;
	}

	public LegElement[] getLegs() {
		return legs;
	}

	private Bounds bounds;

 	public void setBounds(Bounds bounds) {
		this.bounds = bounds;
	}

	public Bounds getBounds() {
		return bounds;
	}

	private String summary;

 	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getSummary() {
		return summary;
	}

	private Object[] waypoint_order;

 	public void setWaypoint_order(Object[] waypoint_order) {
		this.waypoint_order = waypoint_order;
	}

	public Object[] getWaypoint_order() {
		return waypoint_order;
	}

	private Overview_polyline overview_polyline;

 	public void setOverview_polyline(Overview_polyline overview_polyline) {
		this.overview_polyline = overview_polyline;
	}

	public Overview_polyline getOverview_polyline() {
		return overview_polyline;
	}

	private Object[] warnings;

 	public void setWarnings(Object[] warnings) {
		this.warnings = warnings;
	}

	public Object[] getWarnings() {
		return warnings;
	}

	private String copyrights;

 	public void setCopyrights(String copyrights) {
		this.copyrights = copyrights;
	}

	public String getCopyrights() {
		return copyrights;
	}

}