/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package ask.piyush.findnearest.model.direction;

public class StepElement {
	private Distance distance;

 	public void setDistance(Distance distance) {
		this.distance = distance;
	}

	public Distance getDistance() {
		return distance;
	}

	private Duration duration;

 	public void setDuration(Duration duration) {
		this.duration = duration;
	}

	public Duration getDuration() {
		return duration;
	}

	private String travel_mode;

 	public void setTravel_mode(String travel_mode) {
		this.travel_mode = travel_mode;
	}

	public String getTravel_mode() {
		return travel_mode;
	}

	private Polyline polyline;

 	public void setPolyline(Polyline polyline) {
		this.polyline = polyline;
	}

	public Polyline getPolyline() {
		return polyline;
	}

	private Start_location start_location;

 	public void setStart_location(Start_location start_location) {
		this.start_location = start_location;
	}

	public Start_location getStart_location() {
		return start_location;
	}

	private String html_instructions;

 	public void setHtml_instructions(String html_instructions) {
		this.html_instructions = html_instructions;
	}

	public String getHtml_instructions() {
		return html_instructions;
	}

	private End_location end_location;

 	public void setEnd_location(End_location end_location) {
		this.end_location = end_location;
	}

	public End_location getEnd_location() {
		return end_location;
	}

}